/** UOFS Payment Initiation API Uganda Open Finance Standard — Payment
  * Initiation API (Phase 2). Enables authorised Payment Initiation Service
  * Providers (PISPs) to create and manage payments from a PSU's account at an
  * FSP. Covers domestic bank transfers, mobile money transfers (same-MNO and
  * cross-MNO), bill payments, merchant payments, bulk disbursements, and
  * scheduled payments. Every payment follows a consent-then-execute pattern:
  * the PISP creates a payment consent, the PSU authorises it (via OAuth
  * redirect, USSD, or decoupled flow), and then the PISP submits the payment
  * for execution.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package payment.initiation.models

import payment.initiation.models.BillerCategory.*
import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class Biller(
    @named("BillerId") billerId: String,
    @named("BillerName") billerName: String,
    @named("BillerCategory") billerCategory: BillerCategory,
    @named("BillerCode") billerCode: String,
    @named("SupportedPaymentMethods") supportedPaymentMethods: Seq[
      BillerEnums.SupportedPaymentMethods
    ],
    /* Regex pattern for validating customer account numbers */
    @named("AccountNumberFormat") accountNumberFormat: Option[String] =
      scala.None,
    /* Human-readable label for the account number field (e.g., \"Meter Number\") */
    @named("AccountNumberLabel") accountNumberLabel: Option[String] =
      scala.None,
    @named("MinimumAmount") minimumAmount: Option[Amount] = scala.None,
    @named("MaximumAmount") maximumAmount: Option[Amount] = scala.None
)

object BillerEnums:
  enum SupportedPaymentMethods:
    case `BANK_TRANSFER`
    case `MOBILE_WALLET`

  object SupportedPaymentMethods:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
end BillerEnums
