/** UOFS Payment Initiation API Uganda Open Finance Standard — Payment
  * Initiation API (Phase 2). Enables authorised Payment Initiation Service
  * Providers (PISPs) to create and manage payments from a PSU's account at an
  * FSP. Covers domestic bank transfers, mobile money transfers (same-MNO and
  * cross-MNO), bill payments, merchant payments, bulk disbursements, and
  * scheduled payments. Every payment follows a consent-then-execute pattern:
  * the PISP creates a payment consent, the PSU authorises it (via OAuth
  * redirect, USSD, or decoupled flow), and then the PISP submits the payment
  * for execution.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package payment.initiation.models

import java.time.OffsetDateTime
import payment.initiation.models.PaymentStatus.*
import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class BulkPaymentItemStatus(
    @named("PaymentId") paymentId: String,
    @named("InstructionIdentification") instructionIdentification: String,
    @named("Status") status: PaymentStatus,
    @named("InstructedAmount") instructedAmount: Amount,
    @named("StatusUpdateDateTime") statusUpdateDateTime: Option[
      OffsetDateTime
    ] = scala.None,
    @named("StatusReason") statusReason: Option[StatusReason] = scala.None,
    @named("CreditorName") creditorName: Option[String] = scala.None,
    @named("Charges") charges: Option[Seq[Charge]] = scala.None
)

object BulkPaymentItemStatusEnums:
end BulkPaymentItemStatusEnums
