/** UOFS Payment Initiation API Uganda Open Finance Standard — Payment
  * Initiation API (Phase 2). Enables authorised Payment Initiation Service
  * Providers (PISPs) to create and manage payments from a PSU's account at an
  * FSP. Covers domestic bank transfers, mobile money transfers (same-MNO and
  * cross-MNO), bill payments, merchant payments, bulk disbursements, and
  * scheduled payments. Every payment follows a consent-then-execute pattern:
  * the PISP creates a payment consent, the PSU authorises it (via OAuth
  * redirect, USSD, or decoupled flow), and then the PISP submits the payment
  * for execution.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package payment.initiation.models

import java.time.OffsetDateTime
import payment.initiation.models.ChargeBearer.*
import payment.initiation.models.PaymentType.*
import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class PaymentConsentRequestData(
    @named("PaymentType") paymentType: PaymentType,
    /* PISP's unique instruction identifier */
    @named("InstructionIdentification") instructionIdentification: String,
    /* End-to-end reference preserved across all payment legs (ISO 20022 EndToEndId) */
    @named("EndToEndIdentification") endToEndIdentification: String,
    @named("InstructedAmount") instructedAmount: Amount,
    @named("DebtorAccount") debtorAccount: AccountReference,
    @named("CreditorAccount") creditorAccount: AccountReference,
    @named("Purpose") purpose: Purpose,
    @named("RemittanceInformation") remittanceInformation: Option[
      RemittanceInformation
    ] = scala.None,
    /* Required for SCHEDULED payments. Minimum 1 hour, maximum 365 days from now. */
    @named("RequestedExecutionDateTime") requestedExecutionDateTime: Option[
      OffsetDateTime
    ] = scala.None,
    @named("ChargeBearer") chargeBearer: Option[ChargeBearer] = scala.None,
    @named("BillerDetails") billerDetails: Option[BillerDetails] = scala.None,
    @named("RecurrenceDetails") recurrenceDetails: Option[RecurrenceDetails] =
      scala.None
)

object PaymentConsentRequestDataEnums:
end PaymentConsentRequestDataEnums
