/** UOFS Payment Initiation API Uganda Open Finance Standard — Payment
  * Initiation API (Phase 2). Enables authorised Payment Initiation Service
  * Providers (PISPs) to create and manage payments from a PSU's account at an
  * FSP. Covers domestic bank transfers, mobile money transfers (same-MNO and
  * cross-MNO), bill payments, merchant payments, bulk disbursements, and
  * scheduled payments. Every payment follows a consent-then-execute pattern:
  * the PISP creates a payment consent, the PSU authorises it (via OAuth
  * redirect, USSD, or decoupled flow), and then the PISP submits the payment
  * for execution.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package payment.initiation.models

import java.time.OffsetDateTime
import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class PaymentEventNotification(
    @named("notificationId") notificationId: String,
    @named("eventType") eventType: PaymentEventNotificationEnums.EventType,
    @named("eventDateTime") eventDateTime: OffsetDateTime,
    @named("consentId") consentId: String,
    @named(
      "resourceType"
    ) resourceType: PaymentEventNotificationEnums.ResourceType,
    @named("resourceId") resourceId: String,
    @named("data") data: Option[PaymentEventNotificationData] = scala.None,
    @named("links") links: Option[PaymentEventNotificationLinks] = scala.None
)

object PaymentEventNotificationEnums:
  enum EventType:
    case `PaymentStatusChanged`
    case `PaymentAcceptedSettlementCompleted`
    case `PaymentAcceptedCreditSettlementCompleted`
    case `PaymentRejected`
    case `BulkPaymentCompleted`
    case `ScheduledPaymentExecuted`
    case `ScheduledPaymentFailed`

  object EventType:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given eventTypeCodec: JsonValueCodec[EventType] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "PaymentStatusChanged"               => "PaymentStatusChanged"
            case "PaymentAcceptedSettlementCompleted" =>
              "PaymentAcceptedSettlementCompleted"
            case "PaymentAcceptedCreditSettlementCompleted" =>
              "PaymentAcceptedCreditSettlementCompleted"
            case "PaymentRejected"          => "PaymentRejected"
            case "BulkPaymentCompleted"     => "BulkPaymentCompleted"
            case "ScheduledPaymentExecuted" => "ScheduledPaymentExecuted"
            case "ScheduledPaymentFailed"   => "ScheduledPaymentFailed"
        }
        .withDiscriminatorFieldName(scala.None)
    }
  enum ResourceType:
    case `payment`
    case `bulk-payment`
    case `scheduled-payment`

  object ResourceType:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given resourceTypeCodec: JsonValueCodec[ResourceType] =
      JsonCodecMaker.make {
        CodecMakerConfig
          .withAdtLeafClassNameMapper { x =>
            JsonCodecMaker.simpleClassName(x) match
              case "payment"           => "payment"
              case "bulk-payment"      => "bulk-payment"
              case "scheduled-payment" => "scheduled-payment"
          }
          .withDiscriminatorFieldName(scala.None)
      }
end PaymentEventNotificationEnums
