/** UOFS Payment Initiation API Uganda Open Finance Standard — Payment
  * Initiation API (Phase 2). Enables authorised Payment Initiation Service
  * Providers (PISPs) to create and manage payments from a PSU's account at an
  * FSP. Covers domestic bank transfers, mobile money transfers (same-MNO and
  * cross-MNO), bill payments, merchant payments, bulk disbursements, and
  * scheduled payments. Every payment follows a consent-then-execute pattern:
  * the PISP creates a payment consent, the PSU authorises it (via OAuth
  * redirect, USSD, or decoupled flow), and then the PISP submits the payment
  * for execution.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package payment.initiation.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

enum PaymentType:
  case `DOMESTIC_BANK`
  case `BANK_TO_WALLET`
  case `WALLET_TO_BANK`
  case `WALLET_TO_WALLET`
  case `BILL_PAYMENT`
  case `MERCHANT_PAYMENT`
  case `BULK_DISBURSEMENT`
  case `SCHEDULED`

object PaymentType:
  import com.github.plokhotnyuk.jsoniter_scala.macros.*
  import com.github.plokhotnyuk.jsoniter_scala.core.*
  given paymentTypeCodec: JsonValueCodec[PaymentType] = JsonCodecMaker.make {
    CodecMakerConfig
      .withAdtLeafClassNameMapper { x =>
        JsonCodecMaker.simpleClassName(x) match
          case "DOMESTIC_BANK"     => "DOMESTIC_BANK"
          case "BANK_TO_WALLET"    => "BANK_TO_WALLET"
          case "WALLET_TO_BANK"    => "WALLET_TO_BANK"
          case "WALLET_TO_WALLET"  => "WALLET_TO_WALLET"
          case "BILL_PAYMENT"      => "BILL_PAYMENT"
          case "MERCHANT_PAYMENT"  => "MERCHANT_PAYMENT"
          case "BULK_DISBURSEMENT" => "BULK_DISBURSEMENT"
          case "SCHEDULED"         => "SCHEDULED"
      }
      .withDiscriminatorFieldName(scala.None)
  }
end PaymentType
