/** UOFS Payment Initiation API Uganda Open Finance Standard — Payment
  * Initiation API (Phase 2). Enables authorised Payment Initiation Service
  * Providers (PISPs) to create and manage payments from a PSU's account at an
  * FSP. Covers domestic bank transfers, mobile money transfers (same-MNO and
  * cross-MNO), bill payments, merchant payments, bulk disbursements, and
  * scheduled payments. Every payment follows a consent-then-execute pattern:
  * the PISP creates a payment consent, the PSU authorises it (via OAuth
  * redirect, USSD, or decoupled flow), and then the PISP submits the payment
  * for execution.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package payment.initiation.models

import java.time.LocalDate
import payment.initiation.models.StandingOrderFrequency.*
import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class RecurrenceDetails(
    @named("Frequency") frequency: StandingOrderFrequency,
    @named("FirstPaymentDate") firstPaymentDate: LocalDate,
    @named("FinalPaymentDate") finalPaymentDate: Option[LocalDate] = scala.None,
    @named("NumberOfPayments") numberOfPayments: Option[Int] = scala.None,
    @named("RecurringAmount") recurringAmount: Option[Amount] = scala.None
)

object RecurrenceDetailsEnums:
end RecurrenceDetailsEnums
