/** UOFS Payment Initiation API Uganda Open Finance Standard — Payment
  * Initiation API (Phase 2). Enables authorised Payment Initiation Service
  * Providers (PISPs) to create and manage payments from a PSU's account at an
  * FSP. Covers domestic bank transfers, mobile money transfers (same-MNO and
  * cross-MNO), bill payments, merchant payments, bulk disbursements, and
  * scheduled payments. Every payment follows a consent-then-execute pattern:
  * the PISP creates a payment consent, the PSU authorises it (via OAuth
  * redirect, USSD, or decoupled flow), and then the PISP submits the payment
  * for execution.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package payment.initiation.models

import java.time.OffsetDateTime
import payment.initiation.models.PaymentType.*
import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class ScheduledPayment(
    @named("ScheduledPaymentId") scheduledPaymentId: String,
    @named("ConsentId") consentId: String,
    @named("Status") status: ScheduledPaymentEnums.Status,
    @named("PaymentType") paymentType: PaymentType,
    @named("InstructedAmount") instructedAmount: Amount,
    @named("RequestedExecutionDateTime") requestedExecutionDateTime: Option[
      OffsetDateTime
    ] = scala.None,
    @named("CreditorAccount") creditorAccount: Option[AccountReference] =
      scala.None,
    @named("RecurrenceDetails") recurrenceDetails: Option[RecurrenceDetails] =
      scala.None,
    @named("LastExecutionDateTime") lastExecutionDateTime: Option[
      OffsetDateTime
    ] = scala.None,
    @named("NextExecutionDateTime") nextExecutionDateTime: Option[
      OffsetDateTime
    ] = scala.None,
    @named("ExecutionsCompleted") executionsCompleted: Option[Int] = scala.None,
    @named("ExecutionsRemaining") executionsRemaining: Option[Int] = scala.None
)

object ScheduledPaymentEnums:
  enum Status:
    case `SCHEDULED`
    case `EXECUTED`
    case `CANCELLED`
    case `FAILED`

  object Status:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given statusCodec: JsonValueCodec[Status] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "SCHEDULED" => "SCHEDULED"
            case "EXECUTED"  => "EXECUTED"
            case "CANCELLED" => "CANCELLED"
            case "FAILED"    => "FAILED"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end ScheduledPaymentEnums
