/** UOFS Payment Initiation API Uganda Open Finance Standard — Payment
  * Initiation API (Phase 2). Enables authorised Payment Initiation Service
  * Providers (PISPs) to create and manage payments from a PSU's account at an
  * FSP. Covers domestic bank transfers, mobile money transfers (same-MNO and
  * cross-MNO), bill payments, merchant payments, bulk disbursements, and
  * scheduled payments. Every payment follows a consent-then-execute pattern:
  * the PISP creates a payment consent, the PSU authorises it (via OAuth
  * redirect, USSD, or decoupled flow), and then the PISP submits the payment
  * for execution.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package payment.initiation

import payment.initiation.models.*
import java.time.*
import com.github.plokhotnyuk.jsoniter_scala.macros.*
import com.github.plokhotnyuk.jsoniter_scala.core.*
import com.github.plokhotnyuk.jsoniter_scala.circe.JsoniterScalaCodec.*

object JsonSupport extends AdditionalTypeSerializers:
  inline given CodecMakerConfig = CodecMakerConfig.withAllowRecursiveTypes(true)

  inline def deriveJsonCodec[A](using
      inline config: CodecMakerConfig
  ): JsonValueCodec[A] =
    JsonCodecMaker.make(config)

  given bulkPaymentItemListResponseCodec
      : JsonValueCodec[BulkPaymentItemListResponse] = deriveJsonCodec
  given bulkPaymentConsentResponseCodec
      : JsonValueCodec[BulkPaymentConsentResponse] = deriveJsonCodec
  given bulkPaymentExecutionRequestCodec
      : JsonValueCodec[BulkPaymentExecutionRequest] = deriveJsonCodec
  given paymentConsentRequestCodec: JsonValueCodec[PaymentConsentRequest] =
    deriveJsonCodec
  given paymentExecutionRequestCodec: JsonValueCodec[PaymentExecutionRequest] =
    deriveJsonCodec
  given billerListResponseCodec: JsonValueCodec[BillerListResponse] =
    deriveJsonCodec
  given confirmationOfFundsRequestCodec
      : JsonValueCodec[ConfirmationOfFundsRequest] = deriveJsonCodec
  given billerDetailResponseCodec: JsonValueCodec[BillerDetailResponse] =
    deriveJsonCodec
  given scheduledPaymentListResponseCodec
      : JsonValueCodec[ScheduledPaymentListResponse] = deriveJsonCodec
  given paymentConsentResponseCodec: JsonValueCodec[PaymentConsentResponse] =
    deriveJsonCodec
  given paymentResponseCodec: JsonValueCodec[PaymentResponse] = deriveJsonCodec
  given scheduledPaymentResponseCodec
      : JsonValueCodec[ScheduledPaymentResponse] = deriveJsonCodec
  given bulkPaymentConsentRequestCodec
      : JsonValueCodec[BulkPaymentConsentRequest] = deriveJsonCodec
  given bulkPaymentResponseCodec: JsonValueCodec[BulkPaymentResponse] =
    deriveJsonCodec
  given confirmationOfFundsResponseCodec
      : JsonValueCodec[ConfirmationOfFundsResponse] = deriveJsonCodec
