/** UOFS Account Information API Uganda Open Finance Standard — Account
  * Information API (Phase 1). Provides read-only access to account data held at
  * Financial Service Providers (FSPs) on behalf of Payment Service Users (PSUs)
  * who have granted explicit consent to authorised Account Information Service
  * Providers (AISPs). This specification covers banks, mobile money operators,
  * SACCOs, and microfinance institutions. Mobile money and SACCO/MFI extensions
  * are included as optional response fields controlled by consent data
  * categories.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package account.information.api

import account.information.models.AccountDetailResponse
import account.information.models.AccountListResponse
import account.information.models.AccountType.*
import account.information.models.AccountType
import account.information.models.ErrorResponse
import java.time.OffsetDateTime
import java.util.UUID
import account.information.JsonSupport.{*, given}
import account.information.FormSerializable
import account.information.FormStyleFormat
import account.information.HeaderSerializable
import account.information.ApiKeyLocation
import account.information.PathStyleFormat
import account.information.PathSerializable
import account.information.CookieSerializable
import account.information.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object Accounts:
  def apply(
      baseUrl: String = "https://api.example.co.ug/uofs/v1/account-information"
  ): Accounts[account.information.Authorization.NoAuthorization.type] =
    Accounts(baseUrl, account.information.Authorization.NoAuthorization)
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): Accounts[account.information.Authorization.BasicAuth] =
    Accounts(
      baseUrl,
      account.information.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): Accounts[account.information.Authorization.ApiKey] =
    Accounts(baseUrl, account.information.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): Accounts[account.information.Authorization.BearerToken] =
    Accounts(baseUrl, account.information.Authorization.BearerToken(token))

case class Accounts[Auth <: account.information.Authorization] private (
    baseUrl: String,
    authConfig: account.information.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): Accounts[account.information.Authorization.BasicAuth] =
    copy(authConfig =
      account.information.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      apiKey: String
  ): Accounts[account.information.Authorization.ApiKey] =
    copy(authConfig = account.information.Authorization.ApiKey(apiKey))

  def withNoAuth
      : Accounts[account.information.Authorization.NoAuthorization.type] =
    copy(authConfig = account.information.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): Accounts[account.information.Authorization.BearerToken] =
    copy(authConfig = account.information.Authorization.BearerToken(token))

  /** Returns details of a single account. Requires the PROFILE consent
    * category.
    *
    * Expected answers: code 200 : AccountDetailResponse (Account details
    * retrieved successfully) Headers : x-fapi-interaction-id -
    * x-uofs-api-version - x-uofs-request-timestamp - code 401 : ErrorResponse
    * (Missing, expired, or invalid access token) code 403 : ErrorResponse
    * (Consent does not authorise the requested data category, or consent has
    * expired/been revoked) code 404 : ErrorResponse (Resource not found or not
    * accessible under this consent) code 429 : ErrorResponse (Rate limit
    * exceeded) Headers : Retry-After - Seconds to wait before retrying code 500
    * : ErrorResponse (Unexpected server error)
    *
    * Available security schemes: BearerAuth (http)
    *
    * @param accountId
    *   Opaque account identifier as returned by the /accounts endpoint. MUST
    *   NOT be a raw account number or MSISDN.
    * @param xUofsConsentId
    *   Consent artefact ID authorising this request
    * @param xFapiInteractionId
    *   Unique interaction identifier (UUID). If provided in the request, the
    *   FSP MUST echo it. If absent, the FSP MUST generate one.
    * @param xFapiAuthDate
    *   ISO 8601 timestamp of the PSU's last authentication. REQUIRED for Full
    *   Profile.
    * @param xFapiCustomerIpAddress
    *   PSU's IP address if the request is PSU-initiated. Not applicable for
    *   USSD.
    */
  def getAccount(
      accountId: String,
      xUofsConsentId: String,
      xFapiInteractionId: UUID,
      xFapiAuthDate: Option[OffsetDateTime] = scala.None,
      xFapiCustomerIpAddress: Option[String] = scala.None
  )(using
      Auth <:< account.information.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], AccountDetailResponse]
  ] =
    val accountIdPathParam = PathSerializable.serialize(
      "accountId",
      accountId,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/accounts/${accountIdPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .headers(
        HeaderSerializable.serialize("x-uofs-consent-id", xUofsConsentId, false)
      )
      .headers(
        HeaderSerializable.serialize("x-fapi-auth-date", xFapiAuthDate, false)
      )
      .headers(
        HeaderSerializable.serialize(
          "x-fapi-customer-ip-address",
          xFapiCustomerIpAddress,
          false
        )
      )
      .headers(
        HeaderSerializable
          .serialize("x-fapi-interaction-id", xFapiInteractionId, false)
      )
      .auth(authConfig)
      .response(asJson[AccountDetailResponse])

  /** Returns all accounts the PSU has authorised the AISP to access under the
    * active consent. Requires the PROFILE consent category.
    *
    * Expected answers: code 200 : AccountListResponse (Accounts retrieved
    * successfully) Headers : x-fapi-interaction-id - x-uofs-api-version -
    * x-uofs-request-timestamp - code 401 : ErrorResponse (Missing, expired, or
    * invalid access token) code 403 : ErrorResponse (Consent does not authorise
    * the requested data category, or consent has expired/been revoked) code 429
    * : ErrorResponse (Rate limit exceeded) Headers : Retry-After - Seconds to
    * wait before retrying code 500 : ErrorResponse (Unexpected server error)
    *
    * Available security schemes: BearerAuth (http)
    *
    * @param xUofsConsentId
    *   Consent artefact ID authorising this request
    * @param xFapiInteractionId
    *   Unique interaction identifier (UUID). If provided in the request, the
    *   FSP MUST echo it. If absent, the FSP MUST generate one.
    * @param xFapiAuthDate
    *   ISO 8601 timestamp of the PSU's last authentication. REQUIRED for Full
    *   Profile.
    * @param xFapiCustomerIpAddress
    *   PSU's IP address if the request is PSU-initiated. Not applicable for
    *   USSD.
    * @param xUofsPsuDeviceType
    *   Originating device type for audit purposes
    * @param accountType
    *   Filter by account type
    * @param cursor
    *   Opaque pagination cursor from a previous response
    * @param pageSize
    *   Number of items per page
    */
  def getAccounts(
      xUofsConsentId: String,
      xFapiInteractionId: UUID,
      xFapiAuthDate: Option[OffsetDateTime] = scala.None,
      xFapiCustomerIpAddress: Option[String] = scala.None,
      xUofsPsuDeviceType: Option[String] = scala.None,
      accountType: Option[AccountType] = scala.None,
      cursor: Option[String] = scala.None,
      pageSize: Option[Int] = scala.None
  )(using
      Auth <:< account.information.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], AccountListResponse]
  ] =
    val requestURL =
      uri"$baseUrl/accounts"
        .addParams(
          FormSerializable.serialize(
            "accountType",
            accountType,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("cursor", cursor, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("pageSize", pageSize, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .headers(
        HeaderSerializable.serialize("x-uofs-consent-id", xUofsConsentId, false)
      )
      .headers(
        HeaderSerializable.serialize("x-fapi-auth-date", xFapiAuthDate, false)
      )
      .headers(
        HeaderSerializable.serialize(
          "x-fapi-customer-ip-address",
          xFapiCustomerIpAddress,
          false
        )
      )
      .headers(
        HeaderSerializable
          .serialize("x-fapi-interaction-id", xFapiInteractionId, false)
      )
      .headers(
        HeaderSerializable
          .serialize("x-uofs-psu-device-type", xUofsPsuDeviceType, false)
      )
      .auth(authConfig)
      .response(asJson[AccountListResponse])

end Accounts
