/** UOFS Account Information API Uganda Open Finance Standard — Account
  * Information API (Phase 1). Provides read-only access to account data held at
  * Financial Service Providers (FSPs) on behalf of Payment Service Users (PSUs)
  * who have granted explicit consent to authorised Account Information Service
  * Providers (AISPs). This specification covers banks, mobile money operators,
  * SACCOs, and microfinance institutions. Mobile money and SACCO/MFI extensions
  * are included as optional response fields controlled by consent data
  * categories.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package account.information.models

import account.information.models.AccountStatus.*
import account.information.models.AccountSubType.*
import account.information.models.AccountType.*
import java.time.OffsetDateTime
import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class Account(
    /* Opaque, persistent identifier. MUST NOT be the raw account number. */
    @named("AccountId") accountId: String,
    @named("AccountType") accountType: AccountType,
    @named("AccountSubType") accountSubType: AccountSubType,
    @named("Currency") currency: String,
    @named("Status") status: AccountStatus,
    @named("StatusUpdateDateTime") statusUpdateDateTime: OffsetDateTime,
    @named("Description") description: String,
    @named("OpeningDate") openingDate: OffsetDateTime,
    @named("Provider") provider: FSPReference,
    @named("AccountIdentifiers") accountIdentifiers: Seq[AccountIdentifier],
    @named("Nickname") nickname: Option[String] = scala.None,
    @named("ServicerReference") servicerReference: Option[String] = scala.None,
    @named("WalletInfo") walletInfo: Option[WalletInfo] = scala.None,
    @named("AgentSummary") agentSummary: Option[AgentSummary] = scala.None,
    @named("MerchantSummary") merchantSummary: Option[MerchantSummary] =
      scala.None,
    @named("SavingsSummary") savingsSummary: Option[SavingsSummary] =
      scala.None,
    @named("LoanSummary") loanSummary: Option[LoanSummary] = scala.None,
    @named("ShareCapital") shareCapital: Option[ShareCapital] = scala.None
)

object AccountEnums:
end AccountEnums
