/** UOFS Account Information API Uganda Open Finance Standard — Account
  * Information API (Phase 1). Provides read-only access to account data held at
  * Financial Service Providers (FSPs) on behalf of Payment Service Users (PSUs)
  * who have granted explicit consent to authorised Account Information Service
  * Providers (AISPs). This specification covers banks, mobile money operators,
  * SACCOs, and microfinance institutions. Mobile money and SACCO/MFI extensions
  * are included as optional response fields controlled by consent data
  * categories.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package account.information.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

enum AccountType:
  case `CURRENT_ACCOUNT`
  case `SAVINGS_ACCOUNT`
  case `MOBILE_WALLET`
  case `SACCO_SAVINGS`
  case `SACCO_SHARES`
  case `MFI_SAVINGS`
  case `LOAN_ACCOUNT`
  case `VIRTUAL_CARD`

object AccountType:
  import com.github.plokhotnyuk.jsoniter_scala.macros.*
  import com.github.plokhotnyuk.jsoniter_scala.core.*
  given accountTypeCodec: JsonValueCodec[AccountType] = JsonCodecMaker.make {
    CodecMakerConfig
      .withAdtLeafClassNameMapper { x =>
        JsonCodecMaker.simpleClassName(x) match
          case "CURRENT_ACCOUNT" => "CURRENT_ACCOUNT"
          case "SAVINGS_ACCOUNT" => "SAVINGS_ACCOUNT"
          case "MOBILE_WALLET"   => "MOBILE_WALLET"
          case "SACCO_SAVINGS"   => "SACCO_SAVINGS"
          case "SACCO_SHARES"    => "SACCO_SHARES"
          case "MFI_SAVINGS"     => "MFI_SAVINGS"
          case "LOAN_ACCOUNT"    => "LOAN_ACCOUNT"
          case "VIRTUAL_CARD"    => "VIRTUAL_CARD"
      }
      .withDiscriminatorFieldName(scala.None)
  }
end AccountType
