/** UOFS Account Information API Uganda Open Finance Standard — Account
  * Information API (Phase 1). Provides read-only access to account data held at
  * Financial Service Providers (FSPs) on behalf of Payment Service Users (PSUs)
  * who have granted explicit consent to authorised Account Information Service
  * Providers (AISPs). This specification covers banks, mobile money operators,
  * SACCOs, and microfinance institutions. Mobile money and SACCO/MFI extensions
  * are included as optional response fields controlled by consent data
  * categories.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package account.information.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

enum AccountSubType:
  case `INDIVIDUAL`
  case `JOINT`
  case `CORPORATE`
  case `FIXED_DEPOSIT`
  case `PERSONAL`
  case `AGENT`
  case `MERCHANT`
  case `ORDINARY`
  case `FIXED`
  case `JUNIOR`
  case `PREFERENCE`
  case `GROUP`
  case `BUSINESS`
  case `MORTGAGE`
  case `MICRO`
  case `PREPAID`

object AccountSubType:
  import com.github.plokhotnyuk.jsoniter_scala.macros.*
  import com.github.plokhotnyuk.jsoniter_scala.core.*
  given accountSubTypeCodec: JsonValueCodec[AccountSubType] =
    JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "INDIVIDUAL"    => "INDIVIDUAL"
            case "JOINT"         => "JOINT"
            case "CORPORATE"     => "CORPORATE"
            case "FIXED_DEPOSIT" => "FIXED_DEPOSIT"
            case "PERSONAL"      => "PERSONAL"
            case "AGENT"         => "AGENT"
            case "MERCHANT"      => "MERCHANT"
            case "ORDINARY"      => "ORDINARY"
            case "FIXED"         => "FIXED"
            case "JUNIOR"        => "JUNIOR"
            case "PREFERENCE"    => "PREFERENCE"
            case "GROUP"         => "GROUP"
            case "BUSINESS"      => "BUSINESS"
            case "MORTGAGE"      => "MORTGAGE"
            case "MICRO"         => "MICRO"
            case "PREPAID"       => "PREPAID"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end AccountSubType
