/** UOFS Account Information API Uganda Open Finance Standard — Account
  * Information API (Phase 1). Provides read-only access to account data held at
  * Financial Service Providers (FSPs) on behalf of Payment Service Users (PSUs)
  * who have granted explicit consent to authorised Account Information Service
  * Providers (AISPs). This specification covers banks, mobile money operators,
  * SACCOs, and microfinance institutions. Mobile money and SACCO/MFI extensions
  * are included as optional response fields controlled by consent data
  * categories.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package account.information.models

import java.time.OffsetDateTime
import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Agent account details. Included when AGENT_SUMMARY consent category is
  * authorised.
  */
case class AgentSummary(
    @named("AgentId") agentId: Option[String] = scala.None,
    @named("AgentTier") agentTier: Option[AgentSummaryEnums.AgentTier] =
      scala.None,
    @named("FloatBalance") floatBalance: Option[Amount] = scala.None,
    @named("DailyTransactionVolume") dailyTransactionVolume: Option[Int] =
      scala.None,
    @named("DailyTransactionValue") dailyTransactionValue: Option[Amount] =
      scala.None,
    @named("MonthlyCommission") monthlyCommission: Option[Amount] = scala.None,
    @named("CommissionPeriod") commissionPeriod: Option[String] = scala.None,
    @named("ActiveSince") activeSince: Option[OffsetDateTime] = scala.None,
    @named("Territory") territory: Option[String] = scala.None
)

object AgentSummaryEnums:
  enum AgentTier:
    case `STANDARD`
    case `SUPER_AGENT`
    case `MASTER_AGENT`

  object AgentTier:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given agentTierCodec: JsonValueCodec[AgentTier] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "STANDARD"     => "STANDARD"
            case "SUPER_AGENT"  => "SUPER_AGENT"
            case "MASTER_AGENT" => "MASTER_AGENT"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end AgentSummaryEnums
