/** UOFS Account Information API Uganda Open Finance Standard — Account
  * Information API (Phase 1). Provides read-only access to account data held at
  * Financial Service Providers (FSPs) on behalf of Payment Service Users (PSUs)
  * who have granted explicit consent to authorised Account Information Service
  * Providers (AISPs). This specification covers banks, mobile money operators,
  * SACCOs, and microfinance institutions. Mobile money and SACCO/MFI extensions
  * are included as optional response fields controlled by consent data
  * categories.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package account.information.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class Beneficiary(
    @named("BeneficiaryId") beneficiaryId: String,
    @named("AccountId") accountId: String,
    @named("CreditorAccount") creditorAccount: CreditorAccount,
    @named("Reference") reference: Option[String] = scala.None,
    @named("BeneficiaryType") beneficiaryType: Option[
      BeneficiaryEnums.BeneficiaryType
    ] = scala.None
)

object BeneficiaryEnums:
  enum BeneficiaryType:
    case `INDIVIDUAL`
    case `BUSINESS`
    case `GOVERNMENT`

  object BeneficiaryType:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given beneficiaryTypeCodec: JsonValueCodec[BeneficiaryType] =
      JsonCodecMaker.make {
        CodecMakerConfig
          .withAdtLeafClassNameMapper { x =>
            JsonCodecMaker.simpleClassName(x) match
              case "INDIVIDUAL" => "INDIVIDUAL"
              case "BUSINESS"   => "BUSINESS"
              case "GOVERNMENT" => "GOVERNMENT"
          }
          .withDiscriminatorFieldName(scala.None)
      }
end BeneficiaryEnums
