/** UOFS Account Information API Uganda Open Finance Standard — Account
  * Information API (Phase 1). Provides read-only access to account data held at
  * Financial Service Providers (FSPs) on behalf of Payment Service Users (PSUs)
  * who have granted explicit consent to authorised Account Information Service
  * Providers (AISPs). This specification covers banks, mobile money operators,
  * SACCOs, and microfinance institutions. Mobile money and SACCO/MFI extensions
  * are included as optional response fields controlled by consent data
  * categories.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package account.information.models

import java.util.UUID
import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class ErrorResponse(
    @named("Errors") errors: Seq[ErrorResponseErrorsInner],
    /* HTTP status code as string */
    @named("Code") code: String,
    /* Interaction ID for tracing */
    @named("Id") id: UUID,
    /* Summary error message */
    @named("Message") message: String
)
