/** UOFS Account Information API Uganda Open Finance Standard — Account
  * Information API (Phase 1). Provides read-only access to account data held at
  * Financial Service Providers (FSPs) on behalf of Payment Service Users (PSUs)
  * who have granted explicit consent to authorised Account Information Service
  * Providers (AISPs). This specification covers banks, mobile money operators,
  * SACCOs, and microfinance institutions. Mobile money and SACCO/MFI extensions
  * are included as optional response fields controlled by consent data
  * categories.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package account.information.models

import java.time.OffsetDateTime
import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class EventNotification(
    @named("notificationId") notificationId: String,
    @named("eventType") eventType: EventNotificationEnums.EventType,
    @named("eventDateTime") eventDateTime: OffsetDateTime,
    @named("consentId") consentId: String,
    @named("resourceType") resourceType: EventNotificationEnums.ResourceType,
    @named("resourceId") resourceId: Option[String] = scala.None,
    @named("accountId") accountId: Option[String] = scala.None,
    @named("links") links: Option[EventNotificationLinks] = scala.None
)

object EventNotificationEnums:
  enum EventType:
    case `AccountBalanceChanged`
    case `AccountTransactionBooked`
    case `AccountStatusChanged`
    case `ConsentExpired`
    case `ConsentRevoked`

  object EventType:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given eventTypeCodec: JsonValueCodec[EventType] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "AccountBalanceChanged"    => "AccountBalanceChanged"
            case "AccountTransactionBooked" => "AccountTransactionBooked"
            case "AccountStatusChanged"     => "AccountStatusChanged"
            case "ConsentExpired"           => "ConsentExpired"
            case "ConsentRevoked"           => "ConsentRevoked"
        }
        .withDiscriminatorFieldName(scala.None)
    }
  enum ResourceType:
    case `account`
    case `transaction`
    case `balance`
    case `consent`

  object ResourceType:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given resourceTypeCodec: JsonValueCodec[ResourceType] =
      JsonCodecMaker.make {
        CodecMakerConfig
          .withAdtLeafClassNameMapper { x =>
            JsonCodecMaker.simpleClassName(x) match
              case "account"     => "account"
              case "transaction" => "transaction"
              case "balance"     => "balance"
              case "consent"     => "consent"
          }
          .withDiscriminatorFieldName(scala.None)
      }
end EventNotificationEnums
