/** UOFS Account Information API Uganda Open Finance Standard — Account
  * Information API (Phase 1). Provides read-only access to account data held at
  * Financial Service Providers (FSPs) on behalf of Payment Service Users (PSUs)
  * who have granted explicit consent to authorised Account Information Service
  * Providers (AISPs). This specification covers banks, mobile money operators,
  * SACCOs, and microfinance institutions. Mobile money and SACCO/MFI extensions
  * are included as optional response fields controlled by consent data
  * categories.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package account.information.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class FSPReference(
    /* FSP's Participant Directory identifier */
    @named("FSPId") fSPId: String,
    /* FSP's registered name */
    @named("FSPName") fSPName: String,
    @named("FSPType") fSPType: FSPReferenceEnums.FSPType
)

object FSPReferenceEnums:
  enum FSPType:
    case `BANK`
    case `MNO`
    case `SACCO`
    case `MFI`

  object FSPType:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given fSPTypeCodec: JsonValueCodec[FSPType] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "BANK"  => "BANK"
            case "MNO"   => "MNO"
            case "SACCO" => "SACCO"
            case "MFI"   => "MFI"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end FSPReferenceEnums
