/** UOFS Account Information API Uganda Open Finance Standard — Account
  * Information API (Phase 1). Provides read-only access to account data held at
  * Financial Service Providers (FSPs) on behalf of Payment Service Users (PSUs)
  * who have granted explicit consent to authorised Account Information Service
  * Providers (AISPs). This specification covers banks, mobile money operators,
  * SACCOs, and microfinance institutions. Mobile money and SACCO/MFI extensions
  * are included as optional response fields controlled by consent data
  * categories.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package account.information.models

import java.time.OffsetDateTime
import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Loan details. Included when LOAN_SUMMARY consent category is authorised.
  */
case class LoanSummary(
    @named("LoanId") loanId: Option[String] = scala.None,
    @named("LoanType") loanType: Option[LoanSummaryEnums.LoanType] = scala.None,
    @named("DisbursementDate") disbursementDate: Option[OffsetDateTime] =
      scala.None,
    @named("MaturityDate") maturityDate: Option[OffsetDateTime] = scala.None,
    @named("Principal") principal: Option[Amount] = scala.None,
    @named("OutstandingBalance") outstandingBalance: Option[Amount] =
      scala.None,
    @named("InterestRate") interestRate: Option[String] = scala.None,
    @named("InterestType") interestType: Option[LoanSummaryEnums.InterestType] =
      scala.None,
    @named("MonthlyInstalment") monthlyInstalment: Option[Amount] = scala.None,
    @named("NextPaymentDate") nextPaymentDate: Option[OffsetDateTime] =
      scala.None,
    @named("ArrearsStatus") arrearsStatus: Option[
      LoanSummaryEnums.ArrearsStatus
    ] = scala.None,
    @named("ArrearsAmount") arrearsAmount: Option[Amount] = scala.None,
    @named("DaysPastDue") daysPastDue: Option[Int] = scala.None,
    @named("Collateral") collateral: Option[String] = scala.None,
    @named("Guarantors") guarantors: Option[Int] = scala.None
)

object LoanSummaryEnums:
  enum LoanType:
    case `PERSONAL`
    case `BUSINESS`
    case `MORTGAGE`
    case `MICRO`
    case `AGRICULTURAL`
    case `EMERGENCY`

  object LoanType:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given loanTypeCodec: JsonValueCodec[LoanType] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "PERSONAL"     => "PERSONAL"
            case "BUSINESS"     => "BUSINESS"
            case "MORTGAGE"     => "MORTGAGE"
            case "MICRO"        => "MICRO"
            case "AGRICULTURAL" => "AGRICULTURAL"
            case "EMERGENCY"    => "EMERGENCY"
        }
        .withDiscriminatorFieldName(scala.None)
    }
  enum InterestType:
    case `FLAT`
    case `REDUCING_BALANCE`

  object InterestType:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given interestTypeCodec: JsonValueCodec[InterestType] =
      JsonCodecMaker.make {
        CodecMakerConfig
          .withAdtLeafClassNameMapper { x =>
            JsonCodecMaker.simpleClassName(x) match
              case "FLAT"             => "FLAT"
              case "REDUCING_BALANCE" => "REDUCING_BALANCE"
          }
          .withDiscriminatorFieldName(scala.None)
      }
  enum ArrearsStatus:
    case `CURRENT`
    case `WATCH`
    case `SUBSTANDARD`
    case `DOUBTFUL`
    case `LOSS`

  object ArrearsStatus:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given arrearsStatusCodec: JsonValueCodec[ArrearsStatus] =
      JsonCodecMaker.make {
        CodecMakerConfig
          .withAdtLeafClassNameMapper { x =>
            JsonCodecMaker.simpleClassName(x) match
              case "CURRENT"     => "CURRENT"
              case "WATCH"       => "WATCH"
              case "SUBSTANDARD" => "SUBSTANDARD"
              case "DOUBTFUL"    => "DOUBTFUL"
              case "LOSS"        => "LOSS"
          }
          .withDiscriminatorFieldName(scala.None)
      }
end LoanSummaryEnums
