/** UOFS Account Information API Uganda Open Finance Standard — Account
  * Information API (Phase 1). Provides read-only access to account data held at
  * Financial Service Providers (FSPs) on behalf of Payment Service Users (PSUs)
  * who have granted explicit consent to authorised Account Information Service
  * Providers (AISPs). This specification covers banks, mobile money operators,
  * SACCOs, and microfinance institutions. Mobile money and SACCO/MFI extensions
  * are included as optional response fields controlled by consent data
  * categories.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package account.information.models

import java.time.OffsetDateTime
import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Merchant account details. Included when MERCHANT_SUMMARY consent category is
  * authorised.
  */
case class MerchantSummary(
    @named("MerchantId") merchantId: Option[String] = scala.None,
    @named("MerchantName") merchantName: Option[String] = scala.None,
    /* ISO 18245 MCC */
    @named("MerchantCategoryCode") merchantCategoryCode: Option[String] =
      scala.None,
    @named("DailyPaymentVolume") dailyPaymentVolume: Option[Int] = scala.None,
    @named("DailyPaymentValue") dailyPaymentValue: Option[Amount] = scala.None,
    @named("SettlementFrequency") settlementFrequency: Option[
      MerchantSummaryEnums.SettlementFrequency
    ] = scala.None,
    @named("LastSettlementDate") lastSettlementDate: Option[OffsetDateTime] =
      scala.None,
    @named("LastSettlementAmount") lastSettlementAmount: Option[Amount] =
      scala.None,
    @named("ActiveSince") activeSince: Option[OffsetDateTime] = scala.None
)

object MerchantSummaryEnums:
  enum SettlementFrequency:
    case `DAILY`
    case `WEEKLY`
    case `MONTHLY`
    case `ON_DEMAND`

  object SettlementFrequency:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given settlementFrequencyCodec: JsonValueCodec[SettlementFrequency] =
      JsonCodecMaker.make {
        CodecMakerConfig
          .withAdtLeafClassNameMapper { x =>
            JsonCodecMaker.simpleClassName(x) match
              case "DAILY"     => "DAILY"
              case "WEEKLY"    => "WEEKLY"
              case "MONTHLY"   => "MONTHLY"
              case "ON_DEMAND" => "ON_DEMAND"
          }
          .withDiscriminatorFieldName(scala.None)
      }
end MerchantSummaryEnums
