/** UOFS Account Information API Uganda Open Finance Standard — Account
  * Information API (Phase 1). Provides read-only access to account data held at
  * Financial Service Providers (FSPs) on behalf of Payment Service Users (PSUs)
  * who have granted explicit consent to authorised Account Information Service
  * Providers (AISPs). This specification covers banks, mobile money operators,
  * SACCOs, and microfinance institutions. Mobile money and SACCO/MFI extensions
  * are included as optional response fields controlled by consent data
  * categories.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package account.information.models

import java.time.OffsetDateTime
import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** SACCO/MFI savings details. Included when SAVINGS_SUMMARY consent category is
  * authorised.
  */
case class SavingsSummary(
    @named("ContributionFrequency") contributionFrequency: Option[
      SavingsSummaryEnums.ContributionFrequency
    ] = scala.None,
    @named("LastContributionDate") lastContributionDate: Option[
      OffsetDateTime
    ] = scala.None,
    @named("LastContributionAmount") lastContributionAmount: Option[Amount] =
      scala.None,
    @named("TotalContributions") totalContributions: Option[Amount] =
      scala.None,
    @named("InterestEarned") interestEarned: Option[Amount] = scala.None,
    /* Annual interest rate as a percentage string */
    @named("InterestRate") interestRate: Option[String] = scala.None,
    @named("MaturityDate") maturityDate: Option[OffsetDateTime] = scala.None,
    @named("WithdrawalRestrictions") withdrawalRestrictions: Option[String] =
      scala.None
)

object SavingsSummaryEnums:
  enum ContributionFrequency:
    case `WEEKLY`
    case `FORTNIGHTLY`
    case `MONTHLY`
    case `QUARTERLY`

  object ContributionFrequency:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given contributionFrequencyCodec: JsonValueCodec[ContributionFrequency] =
      JsonCodecMaker.make {
        CodecMakerConfig
          .withAdtLeafClassNameMapper { x =>
            JsonCodecMaker.simpleClassName(x) match
              case "WEEKLY"      => "WEEKLY"
              case "FORTNIGHTLY" => "FORTNIGHTLY"
              case "MONTHLY"     => "MONTHLY"
              case "QUARTERLY"   => "QUARTERLY"
          }
          .withDiscriminatorFieldName(scala.None)
      }
end SavingsSummaryEnums
