/** UOFS Account Information API Uganda Open Finance Standard — Account
  * Information API (Phase 1). Provides read-only access to account data held at
  * Financial Service Providers (FSPs) on behalf of Payment Service Users (PSUs)
  * who have granted explicit consent to authorised Account Information Service
  * Providers (AISPs). This specification covers banks, mobile money operators,
  * SACCOs, and microfinance institutions. Mobile money and SACCO/MFI extensions
  * are included as optional response fields controlled by consent data
  * categories.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package account.information.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

enum StandingOrderFrequency:
  case `WEEKLY`
  case `FORTNIGHTLY`
  case `MONTHLY`
  case `QUARTERLY`
  case `SEMI_ANNUALLY`
  case `ANNUALLY`

object StandingOrderFrequency:
  import com.github.plokhotnyuk.jsoniter_scala.macros.*
  import com.github.plokhotnyuk.jsoniter_scala.core.*
  given standingOrderFrequencyCodec: JsonValueCodec[StandingOrderFrequency] =
    JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "WEEKLY"        => "WEEKLY"
            case "FORTNIGHTLY"   => "FORTNIGHTLY"
            case "MONTHLY"       => "MONTHLY"
            case "QUARTERLY"     => "QUARTERLY"
            case "SEMI_ANNUALLY" => "SEMI_ANNUALLY"
            case "ANNUALLY"      => "ANNUALLY"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end StandingOrderFrequency
