/** UOFS Account Information API Uganda Open Finance Standard — Account
  * Information API (Phase 1). Provides read-only access to account data held at
  * Financial Service Providers (FSPs) on behalf of Payment Service Users (PSUs)
  * who have granted explicit consent to authorised Account Information Service
  * Providers (AISPs). This specification covers banks, mobile money operators,
  * SACCOs, and microfinance institutions. Mobile money and SACCO/MFI extensions
  * are included as optional response fields controlled by consent data
  * categories.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package account.information.models

import account.information.models.StandingOrderFrequency.*
import java.time.OffsetDateTime
import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class StandingOrder(
    @named("StandingOrderId") standingOrderId: String,
    @named("AccountId") accountId: String,
    @named("Status") status: StandingOrderEnums.Status,
    @named("Frequency") frequency: StandingOrderFrequency,
    @named("FirstPaymentDateTime") firstPaymentDateTime: OffsetDateTime,
    @named("FirstPaymentAmount") firstPaymentAmount: Amount,
    @named("CreditorAccount") creditorAccount: CreditorAccount,
    @named("Reference") reference: Option[String] = scala.None,
    @named("NextPaymentDateTime") nextPaymentDateTime: Option[OffsetDateTime] =
      scala.None,
    @named("FinalPaymentDateTime") finalPaymentDateTime: Option[
      OffsetDateTime
    ] = scala.None,
    @named("NextPaymentAmount") nextPaymentAmount: Option[Amount] = scala.None,
    @named("FinalPaymentAmount") finalPaymentAmount: Option[Amount] = scala.None
)

object StandingOrderEnums:
  enum Status:
    case `ACTIVE`
    case `INACTIVE`

  object Status:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given statusCodec: JsonValueCodec[Status] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "ACTIVE"   => "ACTIVE"
            case "INACTIVE" => "INACTIVE"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end StandingOrderEnums
