/** UOFS Account Information API Uganda Open Finance Standard — Account
  * Information API (Phase 1). Provides read-only access to account data held at
  * Financial Service Providers (FSPs) on behalf of Payment Service Users (PSUs)
  * who have granted explicit consent to authorised Account Information Service
  * Providers (AISPs). This specification covers banks, mobile money operators,
  * SACCOs, and microfinance institutions. Mobile money and SACCO/MFI extensions
  * are included as optional response fields controlled by consent data
  * categories.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package account.information.models

import account.information.models.CreditDebitIndicator.*
import account.information.models.TransactionStatus.*
import account.information.models.TransactionType.*
import java.time.OffsetDateTime
import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class Transaction(
    @named("TransactionId") transactionId: String,
    @named("AccountId") accountId: String,
    @named("BookingDateTime") bookingDateTime: OffsetDateTime,
    @named("Status") status: TransactionStatus,
    @named("CreditDebitIndicator") creditDebitIndicator: CreditDebitIndicator,
    @named("Amount") amount: Amount,
    @named("TransactionType") transactionType: TransactionType,
    @named("Description") description: String,
    @named("TransactionReference") transactionReference: String,
    @named("ValueDateTime") valueDateTime: Option[OffsetDateTime] = scala.None,
    @named("MerchantDetails") merchantDetails: Option[MerchantDetails] =
      scala.None,
    @named("CounterpartyAccount") counterpartyAccount: Option[
      AccountIdentifier
    ] = scala.None,
    @named("Fee") fee: Option[Amount] = scala.None,
    @named("Balance") balance: Option[TransactionBalance] = scala.None,
    @named("ExchangeRate") exchangeRate: Option[TransactionExchangeRate] =
      scala.None
)

object TransactionEnums:
end TransactionEnums
