/** UOFS Account Information API Uganda Open Finance Standard — Account
  * Information API (Phase 1). Provides read-only access to account data held at
  * Financial Service Providers (FSPs) on behalf of Payment Service Users (PSUs)
  * who have granted explicit consent to authorised Account Information Service
  * Providers (AISPs). This specification covers banks, mobile money operators,
  * SACCOs, and microfinance institutions. Mobile money and SACCO/MFI extensions
  * are included as optional response fields controlled by consent data
  * categories.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package account.information.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

enum TransactionType:
  case `TRANSFER`
  case `PAYMENT`
  case `DEPOSIT`
  case `WITHDRAWAL`
  case `FEE`
  case `INTEREST_CREDIT`
  case `INTEREST_DEBIT`
  case `REVERSAL`
  case `STANDING_ORDER`
  case `DIRECT_DEBIT`
  case `P2P_TRANSFER`
  case `MERCHANT_PAYMENT`
  case `BILL_PAYMENT`
  case `AIRTIME_PURCHASE`
  case `CASH_IN`
  case `CASH_OUT`
  case `BANK_TRANSFER_IN`
  case `BANK_TRANSFER_OUT`
  case `INTERNATIONAL_REMITTANCE`
  case `GOVERNMENT_PAYMENT`
  case `LOAN_DISBURSEMENT`
  case `LOAN_REPAYMENT`
  case `AGENT_FLOAT_TRANSFER`
  case `COMMISSION`
  case `SHARE_PURCHASE`
  case `SHARE_DIVIDEND`
  case `SAVINGS_CONTRIBUTION`
  case `SAVINGS_WITHDRAWAL`
  case `LOAN_PENALTY`
  case `WELFARE_CONTRIBUTION`
  case `WELFARE_PAYOUT`

object TransactionType:
  import com.github.plokhotnyuk.jsoniter_scala.macros.*
  import com.github.plokhotnyuk.jsoniter_scala.core.*
  given transactionTypeCodec: JsonValueCodec[TransactionType] =
    JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "TRANSFER"                 => "TRANSFER"
            case "PAYMENT"                  => "PAYMENT"
            case "DEPOSIT"                  => "DEPOSIT"
            case "WITHDRAWAL"               => "WITHDRAWAL"
            case "FEE"                      => "FEE"
            case "INTEREST_CREDIT"          => "INTEREST_CREDIT"
            case "INTEREST_DEBIT"           => "INTEREST_DEBIT"
            case "REVERSAL"                 => "REVERSAL"
            case "STANDING_ORDER"           => "STANDING_ORDER"
            case "DIRECT_DEBIT"             => "DIRECT_DEBIT"
            case "P2P_TRANSFER"             => "P2P_TRANSFER"
            case "MERCHANT_PAYMENT"         => "MERCHANT_PAYMENT"
            case "BILL_PAYMENT"             => "BILL_PAYMENT"
            case "AIRTIME_PURCHASE"         => "AIRTIME_PURCHASE"
            case "CASH_IN"                  => "CASH_IN"
            case "CASH_OUT"                 => "CASH_OUT"
            case "BANK_TRANSFER_IN"         => "BANK_TRANSFER_IN"
            case "BANK_TRANSFER_OUT"        => "BANK_TRANSFER_OUT"
            case "INTERNATIONAL_REMITTANCE" => "INTERNATIONAL_REMITTANCE"
            case "GOVERNMENT_PAYMENT"       => "GOVERNMENT_PAYMENT"
            case "LOAN_DISBURSEMENT"        => "LOAN_DISBURSEMENT"
            case "LOAN_REPAYMENT"           => "LOAN_REPAYMENT"
            case "AGENT_FLOAT_TRANSFER"     => "AGENT_FLOAT_TRANSFER"
            case "COMMISSION"               => "COMMISSION"
            case "SHARE_PURCHASE"           => "SHARE_PURCHASE"
            case "SHARE_DIVIDEND"           => "SHARE_DIVIDEND"
            case "SAVINGS_CONTRIBUTION"     => "SAVINGS_CONTRIBUTION"
            case "SAVINGS_WITHDRAWAL"       => "SAVINGS_WITHDRAWAL"
            case "LOAN_PENALTY"             => "LOAN_PENALTY"
            case "WELFARE_CONTRIBUTION"     => "WELFARE_CONTRIBUTION"
            case "WELFARE_PAYOUT"           => "WELFARE_PAYOUT"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end TransactionType
