/** UOFS Account Information API Uganda Open Finance Standard — Account
  * Information API (Phase 1). Provides read-only access to account data held at
  * Financial Service Providers (FSPs) on behalf of Payment Service Users (PSUs)
  * who have granted explicit consent to authorised Account Information Service
  * Providers (AISPs). This specification covers banks, mobile money operators,
  * SACCOs, and microfinance institutions. Mobile money and SACCO/MFI extensions
  * are included as optional response fields controlled by consent data
  * categories.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package account.information.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class WalletInfoVirtualCard(
    @named("Available") available: Option[Boolean] = scala.None,
    @named("CardType") cardType: Option[WalletInfoVirtualCardEnums.CardType] =
      scala.None,
    @named("Status") status: Option[WalletInfoVirtualCardEnums.Status] =
      scala.None,
    @named("LastFourDigits") lastFourDigits: Option[String] = scala.None
)

object WalletInfoVirtualCardEnums:
  enum CardType:
    case `PREPAID`

  object CardType:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given cardTypeCodec: JsonValueCodec[CardType] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "PREPAID" => "PREPAID"
        }
        .withDiscriminatorFieldName(scala.None)
    }
  enum Status:
    case `ACTIVE`
    case `INACTIVE`
    case `BLOCKED`

  object Status:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given statusCodec: JsonValueCodec[Status] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "ACTIVE"   => "ACTIVE"
            case "INACTIVE" => "INACTIVE"
            case "BLOCKED"  => "BLOCKED"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end WalletInfoVirtualCardEnums
