/** UOFS Account Information API Uganda Open Finance Standard — Account
  * Information API (Phase 1). Provides read-only access to account data held at
  * Financial Service Providers (FSPs) on behalf of Payment Service Users (PSUs)
  * who have granted explicit consent to authorised Account Information Service
  * Providers (AISPs). This specification covers banks, mobile money operators,
  * SACCOs, and microfinance institutions. Mobile money and SACCO/MFI extensions
  * are included as optional response fields controlled by consent data
  * categories.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package account.information.models

import java.time.OffsetDateTime
import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Mobile money wallet details. Included when WALLET_INFO consent category is
  * authorised.
  */
case class WalletInfo(
    @named("WalletType") walletType: Option[WalletInfoEnums.WalletType] =
      scala.None,
    @named("LinkedMSISDN") linkedMSISDN: Option[String] = scala.None,
    @named("AccountTier") accountTier: Option[WalletInfoEnums.AccountTier] =
      scala.None,
    @named("KYCLevel") kYCLevel: Option[WalletInfoEnums.KYCLevel] = scala.None,
    @named("KYCVerificationDate") kYCVerificationDate: Option[OffsetDateTime] =
      scala.None,
    @named("DailyTransactionLimit") dailyTransactionLimit: Option[Amount] =
      scala.None,
    @named("MaximumBalance") maximumBalance: Option[Amount] = scala.None,
    @named("LinkedBankAccount") linkedBankAccount: Option[
      WalletInfoLinkedBankAccount
    ] = scala.None,
    @named("VirtualCard") virtualCard: Option[WalletInfoVirtualCard] =
      scala.None
)

object WalletInfoEnums:
  enum WalletType:
    case `PERSONAL`
    case `AGENT`
    case `MERCHANT`
    case `CORPORATE`

  object WalletType:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given walletTypeCodec: JsonValueCodec[WalletType] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "PERSONAL"  => "PERSONAL"
            case "AGENT"     => "AGENT"
            case "MERCHANT"  => "MERCHANT"
            case "CORPORATE" => "CORPORATE"
        }
        .withDiscriminatorFieldName(scala.None)
    }
  enum AccountTier:
    case `BASIC`
    case `ENHANCED`
    case `CORPORATE`

  object AccountTier:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given accountTierCodec: JsonValueCodec[AccountTier] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "BASIC"     => "BASIC"
            case "ENHANCED"  => "ENHANCED"
            case "CORPORATE" => "CORPORATE"
        }
        .withDiscriminatorFieldName(scala.None)
    }
  enum KYCLevel:
    case `MINIMAL`
    case `BASIC`
    case `FULL`

  object KYCLevel:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given kYCLevelCodec: JsonValueCodec[KYCLevel] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "MINIMAL" => "MINIMAL"
            case "BASIC"   => "BASIC"
            case "FULL"    => "FULL"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end WalletInfoEnums
