/** UOFS Payment Initiation API Uganda Open Finance Standard — Payment
  * Initiation API (Phase 2). Enables authorised Payment Initiation Service
  * Providers (PISPs) to create and manage payments from a PSU's account at an
  * FSP. Covers domestic bank transfers, mobile money transfers (same-MNO and
  * cross-MNO), bill payments, merchant payments, bulk disbursements, and
  * scheduled payments. Every payment follows a consent-then-execute pattern:
  * the PISP creates a payment consent, the PSU authorises it (via OAuth
  * redirect, USSD, or decoupled flow), and then the PISP submits the payment
  * for execution.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package payment.initiation.api

import payment.initiation.models.BillerCategory.*
import payment.initiation.models.BillerCategory
import payment.initiation.models.BillerDetailResponse
import payment.initiation.models.BillerListResponse
import payment.initiation.models.ErrorResponse
import payment.initiation.JsonSupport.{*, given}
import payment.initiation.FormSerializable
import payment.initiation.FormStyleFormat
import payment.initiation.HeaderSerializable
import payment.initiation.ApiKeyLocation
import payment.initiation.PathStyleFormat
import payment.initiation.PathSerializable
import payment.initiation.CookieSerializable
import payment.initiation.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object BillPayments:
  def apply(
      baseUrl: String = "https://api.example.co.ug/uofs/v1/payment-initiation"
  ): BillPayments[payment.initiation.Authorization.NoAuthorization.type] =
    BillPayments(baseUrl, payment.initiation.Authorization.NoAuthorization)
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): BillPayments[payment.initiation.Authorization.BasicAuth] =
    BillPayments(
      baseUrl,
      payment.initiation.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): BillPayments[payment.initiation.Authorization.ApiKey] =
    BillPayments(baseUrl, payment.initiation.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): BillPayments[payment.initiation.Authorization.BearerToken] =
    BillPayments(baseUrl, payment.initiation.Authorization.BearerToken(token))

case class BillPayments[Auth <: payment.initiation.Authorization] private (
    baseUrl: String,
    authConfig: payment.initiation.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): BillPayments[payment.initiation.Authorization.BasicAuth] =
    copy(authConfig =
      payment.initiation.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      apiKey: String
  ): BillPayments[payment.initiation.Authorization.ApiKey] =
    copy(authConfig = payment.initiation.Authorization.ApiKey(apiKey))

  def withNoAuth
      : BillPayments[payment.initiation.Authorization.NoAuthorization.type] =
    copy(authConfig = payment.initiation.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): BillPayments[payment.initiation.Authorization.BearerToken] =
    copy(authConfig = payment.initiation.Authorization.BearerToken(token))

  /** Returns details of a specific registered biller.
    *
    * Expected answers: code 200 : BillerDetailResponse (Biller details
    * retrieved successfully) code 404 : ErrorResponse (Resource not found) code
    * 500 : ErrorResponse (Unexpected server error)
    *
    * @param billerId
    */
  def getBiller(billerId: String): sttp.client4.Request[
    Either[ResponseException[String], BillerDetailResponse]
  ] =
    val billerIdPathParam = PathSerializable.serialize(
      "billerId",
      billerId,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/billers/${billerIdPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .response(asJson[BillerDetailResponse])

  /** Returns the biller registry. This is a public endpoint that does not
    * require a consent — biller information is not personal data.
    *
    * Expected answers: code 200 : BillerListResponse (Billers retrieved
    * successfully) code 429 : ErrorResponse (Rate limit exceeded) Headers :
    * Retry-After - code 500 : ErrorResponse (Unexpected server error)
    *
    * @param category
    *   Filter by biller category
    * @param search
    *   Search biller name or code
    * @param cursor
    *   Opaque pagination cursor
    * @param pageSize
    */
  def getBillers(
      category: Option[BillerCategory] = scala.None,
      search: Option[String] = scala.None,
      cursor: Option[String] = scala.None,
      pageSize: Option[Int] = scala.None
  ): sttp.client4.Request[
    Either[ResponseException[String], BillerListResponse]
  ] =
    val requestURL =
      uri"$baseUrl/billers"
        .addParams(
          FormSerializable
            .serialize("category", category, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("search", search, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("cursor", cursor, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("pageSize", pageSize, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .response(asJson[BillerListResponse])

end BillPayments
