/** UOFS Payment Initiation API Uganda Open Finance Standard — Payment
  * Initiation API (Phase 2). Enables authorised Payment Initiation Service
  * Providers (PISPs) to create and manage payments from a PSU's account at an
  * FSP. Covers domestic bank transfers, mobile money transfers (same-MNO and
  * cross-MNO), bill payments, merchant payments, bulk disbursements, and
  * scheduled payments. Every payment follows a consent-then-execute pattern:
  * the PISP creates a payment consent, the PSU authorises it (via OAuth
  * redirect, USSD, or decoupled flow), and then the PISP submits the payment
  * for execution.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package payment.initiation.api

import payment.initiation.models.BulkPaymentConsentRequest
import payment.initiation.models.BulkPaymentConsentResponse
import payment.initiation.models.BulkPaymentExecutionRequest
import payment.initiation.models.BulkPaymentItemListResponse
import payment.initiation.models.BulkPaymentResponse
import payment.initiation.models.ErrorResponse
import payment.initiation.models.PaymentStatus.*
import payment.initiation.models.PaymentStatus
import java.util.UUID
import payment.initiation.JsonSupport.{*, given}
import payment.initiation.FormSerializable
import payment.initiation.FormStyleFormat
import payment.initiation.HeaderSerializable
import payment.initiation.ApiKeyLocation
import payment.initiation.PathStyleFormat
import payment.initiation.PathSerializable
import payment.initiation.CookieSerializable
import payment.initiation.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object BulkPayments:
  def apply(
      baseUrl: String = "https://api.example.co.ug/uofs/v1/payment-initiation"
  ): BulkPayments[payment.initiation.Authorization.NoAuthorization.type] =
    BulkPayments(baseUrl, payment.initiation.Authorization.NoAuthorization)
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): BulkPayments[payment.initiation.Authorization.BasicAuth] =
    BulkPayments(
      baseUrl,
      payment.initiation.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): BulkPayments[payment.initiation.Authorization.ApiKey] =
    BulkPayments(baseUrl, payment.initiation.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): BulkPayments[payment.initiation.Authorization.BearerToken] =
    BulkPayments(baseUrl, payment.initiation.Authorization.BearerToken(token))

case class BulkPayments[Auth <: payment.initiation.Authorization] private (
    baseUrl: String,
    authConfig: payment.initiation.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): BulkPayments[payment.initiation.Authorization.BasicAuth] =
    copy(authConfig =
      payment.initiation.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      apiKey: String
  ): BulkPayments[payment.initiation.Authorization.ApiKey] =
    copy(authConfig = payment.initiation.Authorization.ApiKey(apiKey))

  def withNoAuth
      : BulkPayments[payment.initiation.Authorization.NoAuthorization.type] =
    copy(authConfig = payment.initiation.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): BulkPayments[payment.initiation.Authorization.BearerToken] =
    copy(authConfig = payment.initiation.Authorization.BearerToken(token))

  /** Submits an authorised bulk payment consent for execution.
    *
    * Expected answers: code 201 : BulkPaymentResponse (Bulk payment accepted
    * for processing) code 400 : ErrorResponse (Invalid request (field
    * validation, missing fields, amount errors)) code 401 : ErrorResponse
    * (Missing, expired, or invalid access token) code 409 : ErrorResponse
    * (Consent not in AUTHORISED state) code 429 : ErrorResponse (Rate limit
    * exceeded) Headers : Retry-After - code 500 : ErrorResponse (Unexpected
    * server error)
    *
    * Available security schemes: BearerAuth (http)
    *
    * @param xFapiInteractionId
    *   Unique interaction identifier (UUID)
    * @param xIdempotencyKey
    *   UUID v4 generated by the PISP. The FSP MUST store keys for at least 24
    *   hours and return the original response for duplicate requests.
    * @param xUofsConsentId
    *   Consent artefact ID authorising this request
    * @param bulkPaymentExecutionRequest
    */
  def createBulkPayment(
      xFapiInteractionId: UUID,
      xIdempotencyKey: UUID,
      xUofsConsentId: String,
      bulkPaymentExecutionRequest: BulkPaymentExecutionRequest
  )(using
      Auth <:< payment.initiation.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], BulkPaymentResponse]
  ] =
    val requestURL =
      uri"$baseUrl/bulk-payments"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .headers(
        HeaderSerializable
          .serialize("x-fapi-interaction-id", xFapiInteractionId, false)
      )
      .headers(
        HeaderSerializable
          .serialize("x-idempotency-key", xIdempotencyKey, false)
      )
      .headers(
        HeaderSerializable.serialize("x-uofs-consent-id", xUofsConsentId, false)
      )
      .auth(authConfig)
      .body(asJson(bulkPaymentExecutionRequest))
      .response(asJson[BulkPaymentResponse])

  /** Creates a consent for a bulk disbursement containing multiple payments
    * from a single debtor account. Maximum 1,000 payments per batch.
    *
    * Expected answers: code 201 : BulkPaymentConsentResponse (Bulk payment
    * consent created) code 400 : ErrorResponse (Invalid request (field
    * validation, missing fields, amount errors)) code 401 : ErrorResponse
    * (Missing, expired, or invalid access token) code 403 : ErrorResponse
    * (Insufficient consent scope or consent expired/revoked) code 429 :
    * ErrorResponse (Rate limit exceeded) Headers : Retry-After - code 500 :
    * ErrorResponse (Unexpected server error)
    *
    * Available security schemes: BearerAuth (http)
    *
    * @param xFapiInteractionId
    *   Unique interaction identifier (UUID)
    * @param xIdempotencyKey
    *   UUID v4 generated by the PISP. The FSP MUST store keys for at least 24
    *   hours and return the original response for duplicate requests.
    * @param bulkPaymentConsentRequest
    */
  def createBulkPaymentConsent(
      xFapiInteractionId: UUID,
      xIdempotencyKey: UUID,
      bulkPaymentConsentRequest: BulkPaymentConsentRequest
  )(using
      Auth <:< payment.initiation.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], BulkPaymentConsentResponse]
  ] =
    val requestURL =
      uri"$baseUrl/bulk-payment-consents"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .headers(
        HeaderSerializable
          .serialize("x-fapi-interaction-id", xFapiInteractionId, false)
      )
      .headers(
        HeaderSerializable
          .serialize("x-idempotency-key", xIdempotencyKey, false)
      )
      .auth(authConfig)
      .body(asJson(bulkPaymentConsentRequest))
      .response(asJson[BulkPaymentConsentResponse])

  /** Returns aggregate status of the bulk payment.
    *
    * Expected answers: code 200 : BulkPaymentResponse (Bulk payment status
    * retrieved) code 401 : ErrorResponse (Missing, expired, or invalid access
    * token) code 404 : ErrorResponse (Resource not found) code 429 :
    * ErrorResponse (Rate limit exceeded) Headers : Retry-After - code 500 :
    * ErrorResponse (Unexpected server error)
    *
    * Available security schemes: BearerAuth (http)
    *
    * @param bulkPaymentId
    *   Bulk payment identifier
    * @param xFapiInteractionId
    *   Unique interaction identifier (UUID)
    * @param xUofsConsentId
    *   Consent artefact ID authorising this request
    */
  def getBulkPayment(
      bulkPaymentId: String,
      xFapiInteractionId: UUID,
      xUofsConsentId: String
  )(using
      Auth <:< payment.initiation.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], BulkPaymentResponse]
  ] =
    val bulkPaymentIdPathParam = PathSerializable.serialize(
      "bulkPaymentId",
      bulkPaymentId,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/bulk-payments/${bulkPaymentIdPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .headers(
        HeaderSerializable
          .serialize("x-fapi-interaction-id", xFapiInteractionId, false)
      )
      .headers(
        HeaderSerializable.serialize("x-uofs-consent-id", xUofsConsentId, false)
      )
      .auth(authConfig)
      .response(asJson[BulkPaymentResponse])

  /** Returns per-payment statuses within the bulk. Supports pagination.
    *
    * Expected answers: code 200 : BulkPaymentItemListResponse (Individual
    * payment statuses retrieved) code 401 : ErrorResponse (Missing, expired, or
    * invalid access token) code 404 : ErrorResponse (Resource not found) code
    * 429 : ErrorResponse (Rate limit exceeded) Headers : Retry-After - code 500
    * : ErrorResponse (Unexpected server error)
    *
    * Available security schemes: BearerAuth (http)
    *
    * @param bulkPaymentId
    *   Bulk payment identifier
    * @param xFapiInteractionId
    *   Unique interaction identifier (UUID)
    * @param xUofsConsentId
    *   Consent artefact ID authorising this request
    * @param status
    *   Filter by payment status
    * @param cursor
    *   Opaque pagination cursor
    * @param pageSize
    */
  def getBulkPaymentItems(
      bulkPaymentId: String,
      xFapiInteractionId: UUID,
      xUofsConsentId: String,
      status: Option[PaymentStatus] = scala.None,
      cursor: Option[String] = scala.None,
      pageSize: Option[Int] = scala.None
  )(using
      Auth <:< payment.initiation.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], BulkPaymentItemListResponse]
  ] =
    val bulkPaymentIdPathParam = PathSerializable.serialize(
      "bulkPaymentId",
      bulkPaymentId,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/bulk-payments/${bulkPaymentIdPathParam}/payments"
        .addParams(
          FormSerializable
            .serialize("status", status, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("cursor", cursor, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("pageSize", pageSize, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .headers(
        HeaderSerializable
          .serialize("x-fapi-interaction-id", xFapiInteractionId, false)
      )
      .headers(
        HeaderSerializable.serialize("x-uofs-consent-id", xUofsConsentId, false)
      )
      .auth(authConfig)
      .response(asJson[BulkPaymentItemListResponse])

end BulkPayments
