/** UOFS Payment Initiation API Uganda Open Finance Standard — Payment
  * Initiation API (Phase 2). Enables authorised Payment Initiation Service
  * Providers (PISPs) to create and manage payments from a PSU's account at an
  * FSP. Covers domestic bank transfers, mobile money transfers (same-MNO and
  * cross-MNO), bill payments, merchant payments, bulk disbursements, and
  * scheduled payments. Every payment follows a consent-then-execute pattern:
  * the PISP creates a payment consent, the PSU authorises it (via OAuth
  * redirect, USSD, or decoupled flow), and then the PISP submits the payment
  * for execution.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package payment.initiation.api

import payment.initiation.models.ConfirmationOfFundsRequest
import payment.initiation.models.ConfirmationOfFundsResponse
import payment.initiation.models.ErrorResponse
import java.util.UUID
import payment.initiation.JsonSupport.{*, given}
import payment.initiation.FormSerializable
import payment.initiation.FormStyleFormat
import payment.initiation.HeaderSerializable
import payment.initiation.ApiKeyLocation
import payment.initiation.PathStyleFormat
import payment.initiation.PathSerializable
import payment.initiation.CookieSerializable
import payment.initiation.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object ConfirmationOfFunds:
  def apply(
      baseUrl: String = "https://api.example.co.ug/uofs/v1/payment-initiation"
  ): ConfirmationOfFunds[
    payment.initiation.Authorization.NoAuthorization.type
  ] = ConfirmationOfFunds(
    baseUrl,
    payment.initiation.Authorization.NoAuthorization
  )
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): ConfirmationOfFunds[payment.initiation.Authorization.BasicAuth] =
    ConfirmationOfFunds(
      baseUrl,
      payment.initiation.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): ConfirmationOfFunds[payment.initiation.Authorization.ApiKey] =
    ConfirmationOfFunds(
      baseUrl,
      payment.initiation.Authorization.ApiKey(apiKey)
    )

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): ConfirmationOfFunds[payment.initiation.Authorization.BearerToken] =
    ConfirmationOfFunds(
      baseUrl,
      payment.initiation.Authorization.BearerToken(token)
    )

case class ConfirmationOfFunds[
    Auth <: payment.initiation.Authorization
] private (baseUrl: String, authConfig: payment.initiation.Authorization):
  def withBasicAuth(
      username: String,
      password: String
  ): ConfirmationOfFunds[payment.initiation.Authorization.BasicAuth] =
    copy(authConfig =
      payment.initiation.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      apiKey: String
  ): ConfirmationOfFunds[payment.initiation.Authorization.ApiKey] =
    copy(authConfig = payment.initiation.Authorization.ApiKey(apiKey))

  def withNoAuth: ConfirmationOfFunds[
    payment.initiation.Authorization.NoAuthorization.type
  ] =
    copy(authConfig = payment.initiation.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): ConfirmationOfFunds[payment.initiation.Authorization.BearerToken] =
    copy(authConfig = payment.initiation.Authorization.BearerToken(token))

  /** Verifies whether the debtor has sufficient funds for the specified amount
    * (including estimated fees). Does NOT disclose the actual balance. This
    * endpoint is OPTIONAL for FSPs.
    *
    * Expected answers: code 200 : ConfirmationOfFundsResponse (Funds
    * availability checked) code 400 : ErrorResponse (Invalid request (field
    * validation, missing fields, amount errors)) code 401 : ErrorResponse
    * (Missing, expired, or invalid access token) code 403 : ErrorResponse
    * (Insufficient consent scope or consent expired/revoked) code 429 :
    * ErrorResponse (Rate limit exceeded) Headers : Retry-After - code 500 :
    * ErrorResponse (Unexpected server error)
    *
    * Available security schemes: BearerAuth (http)
    *
    * @param xFapiInteractionId
    *   Unique interaction identifier (UUID)
    * @param xUofsConsentId
    *   Consent artefact ID authorising this request
    * @param confirmationOfFundsRequest
    */
  def confirmFunds(
      xFapiInteractionId: UUID,
      xUofsConsentId: String,
      confirmationOfFundsRequest: ConfirmationOfFundsRequest
  )(using
      Auth <:< payment.initiation.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ConfirmationOfFundsResponse]
  ] =
    val requestURL =
      uri"$baseUrl/confirmation-of-funds"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .headers(
        HeaderSerializable
          .serialize("x-fapi-interaction-id", xFapiInteractionId, false)
      )
      .headers(
        HeaderSerializable.serialize("x-uofs-consent-id", xUofsConsentId, false)
      )
      .auth(authConfig)
      .body(asJson(confirmationOfFundsRequest))
      .response(asJson[ConfirmationOfFundsResponse])

end ConfirmationOfFunds
