/** UOFS Payment Initiation API Uganda Open Finance Standard — Payment
  * Initiation API (Phase 2). Enables authorised Payment Initiation Service
  * Providers (PISPs) to create and manage payments from a PSU's account at an
  * FSP. Covers domestic bank transfers, mobile money transfers (same-MNO and
  * cross-MNO), bill payments, merchant payments, bulk disbursements, and
  * scheduled payments. Every payment follows a consent-then-execute pattern:
  * the PISP creates a payment consent, the PSU authorises it (via OAuth
  * redirect, USSD, or decoupled flow), and then the PISP submits the payment
  * for execution.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package payment.initiation.api

import payment.initiation.models.ErrorResponse
import payment.initiation.models.PaymentExecutionRequest
import payment.initiation.models.PaymentResponse
import java.util.UUID
import payment.initiation.JsonSupport.{*, given}
import payment.initiation.FormSerializable
import payment.initiation.FormStyleFormat
import payment.initiation.HeaderSerializable
import payment.initiation.ApiKeyLocation
import payment.initiation.PathStyleFormat
import payment.initiation.PathSerializable
import payment.initiation.CookieSerializable
import payment.initiation.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object Payments:
  def apply(
      baseUrl: String = "https://api.example.co.ug/uofs/v1/payment-initiation"
  ): Payments[payment.initiation.Authorization.NoAuthorization.type] =
    Payments(baseUrl, payment.initiation.Authorization.NoAuthorization)
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): Payments[payment.initiation.Authorization.BasicAuth] =
    Payments(
      baseUrl,
      payment.initiation.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): Payments[payment.initiation.Authorization.ApiKey] =
    Payments(baseUrl, payment.initiation.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): Payments[payment.initiation.Authorization.BearerToken] =
    Payments(baseUrl, payment.initiation.Authorization.BearerToken(token))

case class Payments[Auth <: payment.initiation.Authorization] private (
    baseUrl: String,
    authConfig: payment.initiation.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): Payments[payment.initiation.Authorization.BasicAuth] =
    copy(authConfig =
      payment.initiation.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      apiKey: String
  ): Payments[payment.initiation.Authorization.ApiKey] =
    copy(authConfig = payment.initiation.Authorization.ApiKey(apiKey))

  def withNoAuth
      : Payments[payment.initiation.Authorization.NoAuthorization.type] =
    copy(authConfig = payment.initiation.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): Payments[payment.initiation.Authorization.BearerToken] =
    copy(authConfig = payment.initiation.Authorization.BearerToken(token))

  /** Submits an authorised payment consent for execution. The referenced
    * consent MUST have status AUTHORISED. Payment details are drawn from the
    * consent — they are not repeated in the request body.
    *
    * Expected answers: code 201 : PaymentResponse (Payment accepted for
    * processing) Headers : x-fapi-interaction-id - x-uofs-api-version - code
    * 400 : ErrorResponse (Invalid request (field validation, missing fields,
    * amount errors)) code 401 : ErrorResponse (Missing, expired, or invalid
    * access token) code 403 : ErrorResponse (Insufficient consent scope or
    * consent expired/revoked) code 409 : ErrorResponse (Consent not in
    * AUTHORISED state, or duplicate submission) code 422 : ErrorResponse
    * (Consent has expired before payment submission) code 429 : ErrorResponse
    * (Rate limit exceeded) Headers : Retry-After - code 500 : ErrorResponse
    * (Unexpected server error)
    *
    * Available security schemes: BearerAuth (http)
    *
    * @param xFapiInteractionId
    *   Unique interaction identifier (UUID)
    * @param xIdempotencyKey
    *   UUID v4 generated by the PISP. The FSP MUST store keys for at least 24
    *   hours and return the original response for duplicate requests.
    * @param xUofsConsentId
    *   Consent artefact ID authorising this request
    * @param paymentExecutionRequest
    */
  def createPayment(
      xFapiInteractionId: UUID,
      xIdempotencyKey: UUID,
      xUofsConsentId: String,
      paymentExecutionRequest: PaymentExecutionRequest
  )(using
      Auth <:< payment.initiation.Authorization.BearerToken
  ): sttp.client4.Request[Either[ResponseException[String], PaymentResponse]] =
    val requestURL =
      uri"$baseUrl/payments"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .headers(
        HeaderSerializable
          .serialize("x-fapi-interaction-id", xFapiInteractionId, false)
      )
      .headers(
        HeaderSerializable
          .serialize("x-idempotency-key", xIdempotencyKey, false)
      )
      .headers(
        HeaderSerializable.serialize("x-uofs-consent-id", xUofsConsentId, false)
      )
      .auth(authConfig)
      .body(asJson(paymentExecutionRequest))
      .response(asJson[PaymentResponse])

  /** Returns the current state of a submitted payment.
    *
    * Expected answers: code 200 : PaymentResponse (Payment status retrieved
    * successfully) code 401 : ErrorResponse (Missing, expired, or invalid
    * access token) code 404 : ErrorResponse (Resource not found) code 429 :
    * ErrorResponse (Rate limit exceeded) Headers : Retry-After - code 500 :
    * ErrorResponse (Unexpected server error)
    *
    * Available security schemes: BearerAuth (http)
    *
    * @param paymentId
    *   Payment identifier returned after submission
    * @param xFapiInteractionId
    *   Unique interaction identifier (UUID)
    * @param xUofsConsentId
    *   Consent artefact ID authorising this request
    */
  def getPayment(
      paymentId: String,
      xFapiInteractionId: UUID,
      xUofsConsentId: String
  )(using
      Auth <:< payment.initiation.Authorization.BearerToken
  ): sttp.client4.Request[Either[ResponseException[String], PaymentResponse]] =
    val paymentIdPathParam = PathSerializable.serialize(
      "paymentId",
      paymentId,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/payments/${paymentIdPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .headers(
        HeaderSerializable
          .serialize("x-fapi-interaction-id", xFapiInteractionId, false)
      )
      .headers(
        HeaderSerializable.serialize("x-uofs-consent-id", xUofsConsentId, false)
      )
      .auth(authConfig)
      .response(asJson[PaymentResponse])

end Payments
