/** UOFS Payment Initiation API Uganda Open Finance Standard — Payment
  * Initiation API (Phase 2). Enables authorised Payment Initiation Service
  * Providers (PISPs) to create and manage payments from a PSU's account at an
  * FSP. Covers domestic bank transfers, mobile money transfers (same-MNO and
  * cross-MNO), bill payments, merchant payments, bulk disbursements, and
  * scheduled payments. Every payment follows a consent-then-execute pattern:
  * the PISP creates a payment consent, the PSU authorises it (via OAuth
  * redirect, USSD, or decoupled flow), and then the PISP submits the payment
  * for execution.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package payment.initiation.api

import payment.initiation.models.ErrorResponse
import payment.initiation.models.PaymentConsentRequest
import payment.initiation.models.PaymentConsentResponse
import java.util.UUID
import payment.initiation.JsonSupport.{*, given}
import payment.initiation.FormSerializable
import payment.initiation.FormStyleFormat
import payment.initiation.HeaderSerializable
import payment.initiation.ApiKeyLocation
import payment.initiation.PathStyleFormat
import payment.initiation.PathSerializable
import payment.initiation.CookieSerializable
import payment.initiation.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object PaymentConsents:
  def apply(
      baseUrl: String = "https://api.example.co.ug/uofs/v1/payment-initiation"
  ): PaymentConsents[payment.initiation.Authorization.NoAuthorization.type] =
    PaymentConsents(baseUrl, payment.initiation.Authorization.NoAuthorization)
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): PaymentConsents[payment.initiation.Authorization.BasicAuth] =
    PaymentConsents(
      baseUrl,
      payment.initiation.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): PaymentConsents[payment.initiation.Authorization.ApiKey] =
    PaymentConsents(baseUrl, payment.initiation.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): PaymentConsents[payment.initiation.Authorization.BearerToken] =
    PaymentConsents(
      baseUrl,
      payment.initiation.Authorization.BearerToken(token)
    )

case class PaymentConsents[Auth <: payment.initiation.Authorization] private (
    baseUrl: String,
    authConfig: payment.initiation.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): PaymentConsents[payment.initiation.Authorization.BasicAuth] =
    copy(authConfig =
      payment.initiation.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      apiKey: String
  ): PaymentConsents[payment.initiation.Authorization.ApiKey] =
    copy(authConfig = payment.initiation.Authorization.ApiKey(apiKey))

  def withNoAuth
      : PaymentConsents[payment.initiation.Authorization.NoAuthorization.type] =
    copy(authConfig = payment.initiation.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): PaymentConsents[payment.initiation.Authorization.BearerToken] =
    copy(authConfig = payment.initiation.Authorization.BearerToken(token))

  /** Cancels a payment consent that has not yet been executed. Only valid when
    * the consent status is PENDING or AUTHORISED.
    *
    * Expected answers: code 204 : (Payment consent cancelled successfully) code
    * 401 : ErrorResponse (Missing, expired, or invalid access token) code 404 :
    * ErrorResponse (Resource not found) code 409 : ErrorResponse (Consent
    * cannot be cancelled (already executed or in terminal state)) code 500 :
    * ErrorResponse (Unexpected server error)
    *
    * Available security schemes: BearerAuth (http)
    *
    * @param consentId
    *   Payment consent identifier
    * @param xFapiInteractionId
    *   Unique interaction identifier (UUID)
    */
  def cancelPaymentConsent(consentId: String, xFapiInteractionId: UUID)(using
      Auth <:< payment.initiation.Authorization.BearerToken
  ): sttp.client4.Request[Either[ResponseException[String], Unit]] =
    val consentIdPathParam = PathSerializable.serialize(
      "consentId",
      consentId,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/payment-consents/${consentIdPathParam}"

    basicRequest
      .method(Method.DELETE, requestURL)
      .contentType("application/json")
      .headers(
        HeaderSerializable
          .serialize("x-fapi-interaction-id", xFapiInteractionId, false)
      )
      .auth(authConfig)
      .response(
        asString.mapWithMetadata(
          ResponseAs.deserializeRightWithError(_ => Right(()))
        )
      )

  /** Creates a new payment consent that the PSU must authorise before the
    * payment can be executed. The FSP returns fee disclosure in the response.
    *
    * Expected answers: code 201 : PaymentConsentResponse (Payment consent
    * created successfully) Headers : x-fapi-interaction-id - x-uofs-api-version -
    * code 400 : ErrorResponse (Invalid request (field validation, missing
    * fields, amount errors)) code 401 : ErrorResponse (Missing, expired, or
    * invalid access token) code 403 : ErrorResponse (Insufficient consent scope
    * or consent expired/revoked) code 429 : ErrorResponse (Rate limit exceeded)
    * Headers : Retry-After - code 500 : ErrorResponse (Unexpected server error)
    *
    * Available security schemes: BearerAuth (http)
    *
    * @param xFapiInteractionId
    *   Unique interaction identifier (UUID)
    * @param xIdempotencyKey
    *   UUID v4 generated by the PISP. The FSP MUST store keys for at least 24
    *   hours and return the original response for duplicate requests.
    * @param paymentConsentRequest
    */
  def createPaymentConsent(
      xFapiInteractionId: UUID,
      xIdempotencyKey: UUID,
      paymentConsentRequest: PaymentConsentRequest
  )(using
      Auth <:< payment.initiation.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], PaymentConsentResponse]
  ] =
    val requestURL =
      uri"$baseUrl/payment-consents"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .headers(
        HeaderSerializable
          .serialize("x-fapi-interaction-id", xFapiInteractionId, false)
      )
      .headers(
        HeaderSerializable
          .serialize("x-idempotency-key", xIdempotencyKey, false)
      )
      .auth(authConfig)
      .body(asJson(paymentConsentRequest))
      .response(asJson[PaymentConsentResponse])

  /** Returns the current state of a payment consent.
    *
    * Expected answers: code 200 : PaymentConsentResponse (Payment consent
    * retrieved successfully) code 401 : ErrorResponse (Missing, expired, or
    * invalid access token) code 404 : ErrorResponse (Resource not found) code
    * 429 : ErrorResponse (Rate limit exceeded) Headers : Retry-After - code 500
    * : ErrorResponse (Unexpected server error)
    *
    * Available security schemes: BearerAuth (http)
    *
    * @param consentId
    *   Payment consent identifier
    * @param xFapiInteractionId
    *   Unique interaction identifier (UUID)
    */
  def getPaymentConsent(consentId: String, xFapiInteractionId: UUID)(using
      Auth <:< payment.initiation.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], PaymentConsentResponse]
  ] =
    val consentIdPathParam = PathSerializable.serialize(
      "consentId",
      consentId,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/payment-consents/${consentIdPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .headers(
        HeaderSerializable
          .serialize("x-fapi-interaction-id", xFapiInteractionId, false)
      )
      .auth(authConfig)
      .response(asJson[PaymentConsentResponse])

end PaymentConsents
