/** UOFS Payment Initiation API Uganda Open Finance Standard — Payment
  * Initiation API (Phase 2). Enables authorised Payment Initiation Service
  * Providers (PISPs) to create and manage payments from a PSU's account at an
  * FSP. Covers domestic bank transfers, mobile money transfers (same-MNO and
  * cross-MNO), bill payments, merchant payments, bulk disbursements, and
  * scheduled payments. Every payment follows a consent-then-execute pattern:
  * the PISP creates a payment consent, the PSU authorises it (via OAuth
  * redirect, USSD, or decoupled flow), and then the PISP submits the payment
  * for execution.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package payment.initiation.api

import payment.initiation.models.ErrorResponse
import payment.initiation.models.ScheduledPaymentListResponse
import payment.initiation.models.ScheduledPaymentResponse
import java.util.UUID
import payment.initiation.JsonSupport.{*, given}
import payment.initiation.FormSerializable
import payment.initiation.FormStyleFormat
import payment.initiation.HeaderSerializable
import payment.initiation.ApiKeyLocation
import payment.initiation.PathStyleFormat
import payment.initiation.PathSerializable
import payment.initiation.CookieSerializable
import payment.initiation.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object ScheduledPayments:
  def apply(
      baseUrl: String = "https://api.example.co.ug/uofs/v1/payment-initiation"
  ): ScheduledPayments[payment.initiation.Authorization.NoAuthorization.type] =
    ScheduledPayments(baseUrl, payment.initiation.Authorization.NoAuthorization)
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): ScheduledPayments[payment.initiation.Authorization.BasicAuth] =
    ScheduledPayments(
      baseUrl,
      payment.initiation.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): ScheduledPayments[payment.initiation.Authorization.ApiKey] =
    ScheduledPayments(baseUrl, payment.initiation.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): ScheduledPayments[payment.initiation.Authorization.BearerToken] =
    ScheduledPayments(
      baseUrl,
      payment.initiation.Authorization.BearerToken(token)
    )

case class ScheduledPayments[Auth <: payment.initiation.Authorization] private (
    baseUrl: String,
    authConfig: payment.initiation.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): ScheduledPayments[payment.initiation.Authorization.BasicAuth] =
    copy(authConfig =
      payment.initiation.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      apiKey: String
  ): ScheduledPayments[payment.initiation.Authorization.ApiKey] =
    copy(authConfig = payment.initiation.Authorization.ApiKey(apiKey))

  def withNoAuth: ScheduledPayments[
    payment.initiation.Authorization.NoAuthorization.type
  ] =
    copy(authConfig = payment.initiation.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): ScheduledPayments[payment.initiation.Authorization.BearerToken] =
    copy(authConfig = payment.initiation.Authorization.BearerToken(token))

  /** Cancels a scheduled payment before its execution date.
    *
    * Expected answers: code 204 : (Scheduled payment cancelled successfully)
    * code 401 : ErrorResponse (Missing, expired, or invalid access token) code
    * 404 : ErrorResponse (Resource not found) code 409 : ErrorResponse (Payment
    * has already been executed or is in processing) code 500 : ErrorResponse
    * (Unexpected server error)
    *
    * Available security schemes: BearerAuth (http)
    *
    * @param scheduledPaymentId
    *   Scheduled payment identifier
    * @param xFapiInteractionId
    *   Unique interaction identifier (UUID)
    * @param xUofsConsentId
    *   Consent artefact ID authorising this request
    */
  def cancelScheduledPayment(
      scheduledPaymentId: String,
      xFapiInteractionId: UUID,
      xUofsConsentId: String
  )(using
      Auth <:< payment.initiation.Authorization.BearerToken
  ): sttp.client4.Request[Either[ResponseException[String], Unit]] =
    val scheduledPaymentIdPathParam = PathSerializable.serialize(
      "scheduledPaymentId",
      scheduledPaymentId,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/scheduled-payments/${scheduledPaymentIdPathParam}"

    basicRequest
      .method(Method.DELETE, requestURL)
      .contentType("application/json")
      .headers(
        HeaderSerializable
          .serialize("x-fapi-interaction-id", xFapiInteractionId, false)
      )
      .headers(
        HeaderSerializable.serialize("x-uofs-consent-id", xUofsConsentId, false)
      )
      .auth(authConfig)
      .response(
        asString.mapWithMetadata(
          ResponseAs.deserializeRightWithError(_ => Right(()))
        )
      )

  /** Returns details of a specific scheduled payment.
    *
    * Expected answers: code 200 : ScheduledPaymentResponse (Scheduled payment
    * details retrieved) code 401 : ErrorResponse (Missing, expired, or invalid
    * access token) code 404 : ErrorResponse (Resource not found) code 429 :
    * ErrorResponse (Rate limit exceeded) Headers : Retry-After - code 500 :
    * ErrorResponse (Unexpected server error)
    *
    * Available security schemes: BearerAuth (http)
    *
    * @param scheduledPaymentId
    *   Scheduled payment identifier
    * @param xFapiInteractionId
    *   Unique interaction identifier (UUID)
    * @param xUofsConsentId
    *   Consent artefact ID authorising this request
    */
  def getScheduledPayment(
      scheduledPaymentId: String,
      xFapiInteractionId: UUID,
      xUofsConsentId: String
  )(using
      Auth <:< payment.initiation.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ScheduledPaymentResponse]
  ] =
    val scheduledPaymentIdPathParam = PathSerializable.serialize(
      "scheduledPaymentId",
      scheduledPaymentId,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/scheduled-payments/${scheduledPaymentIdPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .headers(
        HeaderSerializable
          .serialize("x-fapi-interaction-id", xFapiInteractionId, false)
      )
      .headers(
        HeaderSerializable.serialize("x-uofs-consent-id", xUofsConsentId, false)
      )
      .auth(authConfig)
      .response(asJson[ScheduledPaymentResponse])

  /** Returns all active scheduled payments under the consent.
    *
    * Expected answers: code 200 : ScheduledPaymentListResponse (Scheduled
    * payments retrieved) code 401 : ErrorResponse (Missing, expired, or invalid
    * access token) code 403 : ErrorResponse (Insufficient consent scope or
    * consent expired/revoked) code 429 : ErrorResponse (Rate limit exceeded)
    * Headers : Retry-After - code 500 : ErrorResponse (Unexpected server error)
    *
    * Available security schemes: BearerAuth (http)
    *
    * @param xUofsConsentId
    *   Consent artefact ID authorising this request
    * @param xFapiInteractionId
    *   Unique interaction identifier (UUID)
    * @param cursor
    *   Opaque pagination cursor
    * @param pageSize
    */
  def getScheduledPayments(
      xUofsConsentId: String,
      xFapiInteractionId: UUID,
      cursor: Option[String] = scala.None,
      pageSize: Option[Int] = scala.None
  )(using
      Auth <:< payment.initiation.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ScheduledPaymentListResponse]
  ] =
    val requestURL =
      uri"$baseUrl/scheduled-payments"
        .addParams(
          FormSerializable
            .serialize("cursor", cursor, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("pageSize", pageSize, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .headers(
        HeaderSerializable.serialize("x-uofs-consent-id", xUofsConsentId, false)
      )
      .headers(
        HeaderSerializable
          .serialize("x-fapi-interaction-id", xFapiInteractionId, false)
      )
      .auth(authConfig)
      .response(asJson[ScheduledPaymentListResponse])

end ScheduledPayments
