/** UOFS Account Information API Uganda Open Finance Standard — Account
  * Information API (Phase 1). Provides read-only access to account data held at
  * Financial Service Providers (FSPs) on behalf of Payment Service Users (PSUs)
  * who have granted explicit consent to authorised Account Information Service
  * Providers (AISPs). This specification covers banks, mobile money operators,
  * SACCOs, and microfinance institutions. Mobile money and SACCO/MFI extensions
  * are included as optional response fields controlled by consent data
  * categories.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package account.information

import account.information.models.*
import java.time.*
import com.github.plokhotnyuk.jsoniter_scala.macros.*
import com.github.plokhotnyuk.jsoniter_scala.core.*
import com.github.plokhotnyuk.jsoniter_scala.circe.JsoniterScalaCodec.*

object JsonSupport extends AdditionalTypeSerializers:
  inline given CodecMakerConfig = CodecMakerConfig.withAllowRecursiveTypes(true)

  inline def deriveJsonCodec[A](using
      inline config: CodecMakerConfig
  ): JsonValueCodec[A] =
    JsonCodecMaker.make(config)

  given directDebitListResponseCodec: JsonValueCodec[DirectDebitListResponse] =
    deriveJsonCodec
  given beneficiaryListResponseCodec: JsonValueCodec[BeneficiaryListResponse] =
    deriveJsonCodec
  given standingOrderListResponseCodec
      : JsonValueCodec[StandingOrderListResponse] = deriveJsonCodec
  given accountListResponseCodec: JsonValueCodec[AccountListResponse] =
    deriveJsonCodec
  given accountDetailResponseCodec: JsonValueCodec[AccountDetailResponse] =
    deriveJsonCodec
  given transactionListResponseCodec: JsonValueCodec[TransactionListResponse] =
    deriveJsonCodec
  given balanceListResponseCodec: JsonValueCodec[BalanceListResponse] =
    deriveJsonCodec
